In [1]:
import wooldridge as woo
import numpy as np
import pandas as pd
import patsy as pt

gpa1 = woo.dataWoo('gpa1')

In [2]:
gpa1.head()

age  soph  junior  senior  senior5  male  campus  business  engineer  \
0   21     0       0       1        0     0       0         1         0   
1   21     0       0       1        0     0       0         1         0   
2   20     0       1       0        0     0       0         1         0   
3   19     1       0       0        0     1       1         1         0   
4   20     0       1       0        0     0       0         1         0   

   colGPA  ...  greek  car  siblings  bgfriend  clubs  skipped  alcohol  \
0     3.0  ...      0    1         1         0      0      2.0      1.0   
1     3.4  ...      0    1         0         1      1      0.0      1.0   
2     3.0  ...      0    1         1         0      1      0.0      1.0   
3     3.5  ...      0    0         1         0      0      0.0      0.0   
4     3.6  ...      0    1         1         1      0      0.0      1.5   

   gradMI  fathcoll  mothcoll  
0       1         0         0  
1       1         1         1  
2       1         1         1  
3       0         0         0  
4       1         1         0  

[5 rows x 29 columns]

In [3]:
n = len(gpa1)
k = 2

In [4]:
y = gpa1['colGPA']

In [5]:
X = pd.DataFrame({'const': 1, 'hsGPA': gpa1['hsGPA'], 'ACT': gpa1['ACT']})
X.head()

const  hsGPA  ACT
0      1    3.0   21
1      1    3.2   24
2      1    3.6   26
3      1    3.5   27
4      1    3.9   28

In [6]:
X = np.array(X)
y = np.array(y).reshape(n, 1)
b = np.linalg.inv(X.T @ X) @ X.T @ y

In [7]:
b

array([[1.28632777],
       [0.45345589],
       [0.00942601]])

In [8]:
u_hat = y - X @ b
sigsq_hat = (u_hat.T @ u_hat) / (n - k - 1)

In [9]:
SER = np.sqrt(sigsq_hat)
SER

array([[0.34031576]])

In [10]:
Vbeta_hat = sigsq_hat * np.linalg.inv(X.T @ X)
se = np.sqrt(np.diagonal(Vbeta_hat))
print(se)

[0.34082212 0.09581292 0.01077719]
